[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
